GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5e95f1ac1ad1b728e4bbdeb7

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/5e95f1ac1ad1b728e4bbdeb7

###

PATCH http://localhost:3000/subscribers/5e95f71f519a203b18c03aaa
Content-type: application/json

{
    "name": "New Name"
}